### ISSUE TITLE
Unexpected identifier error

### ISSUE THREAD

**Issue by samoinsecure** [pxoss/proxybot.js#1]
Hi,

i tried running your script but i'm getting this error message, i tried but no luck with fixing it.

> /Desktop/ccommands/proxy.js:1
> (function (exports, require, module, __filename, __dirname) { onst Discord = require("discord.js");
>                                                                    ^^^^^^^
> 
> SyntaxError: Unexpected identifier
>     at createScript (vm.js:80:10)
>     at Object.runInThisContext (vm.js:139:10)
>     at Module._compile (module.js:617:28)
>     at Object.Module._extensions..js (module.js:664:10)
>     at Module.load (module.js:566:32)
>     at tryModuleLoad (module.js:506:12)
>     at Function.Module._load (module.js:498:3)
>     at Function.Module.runMain (module.js:694:10)
>     at startup (bootstrap_node.js:204:16)
>     at bootstrap_node.js:625:3

**Comment by pxoss** [comment]
The way i see, you are trying to add the proxybot into your bot. The proxy bot is all in one, and includes the login. You will have to just modify the code so that it works as a separate command.

**Comment by samoinsecure** [comment]
Just tried exacctly what you said and still doesn't work for some reason. I modified the bot token & prefix and I'm still having the issue.

<img width="1091" alt="Screenshot 2019-04-17 at 23 53 16" src="https://user-images.githubusercontent.com/26344980/56323472-47c58500-616c-11e9-81fa-51a38a8ae5ab.png">

**Comment by samoinsecure** [comment]
Could you please check it out? I'd be much thankful

**Comment by pxoss** [comment]
The file is called app.js the project is called proxybot.js just try node app.js

**Comment by samoinsecure** [comment]
Can't believe I'm really this stupid, it works now lol. Thank you
